[tool.poetry]
name = "skillboxcurse"
version = "0.1.0"
description = ""
authors = ["Забутный Юрий <zabutniy10@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
